language: cpp
dist: trusty
sudo: false

matrix:
  include:
   # Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7', 'expat', 'libgmp-dev']
      env: GCCVER='7' CXX_COMPILER='g++-7' C_COMPILER='gcc-7'

    # 4/ OSX GCC Builds
    - os: osx
      osx_image: xcode8.3
      compiler: gcc
      env: GCCVER='7' CXX_COMPILER='g++-7' C_COMPILER='gcc-7'

before_script:
## OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm /usr/local/include/c++         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc gmp  expat      ; fi  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export TARGETBRANCH=osx ; fi
  - cd ${TRAVIS_BUILD_DIR}
  - export CXX=${CXX_COMPILER}
  - export CC=${C_COMPILER}
  # linux only
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export AR=gcc-ar-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RANLIB=gcc-ranlib-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export NM=gcc-nm-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export TARGETBRANCH=gh-pages ; fi


script :
  - /bin/bash ./antlr.sh
  - /bin/sh ./tag.sh
  - autoreconf -vfi
#  - mkdir usr && mkdir usr/local
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --progress=dot:mega https://lip6.github.io/libDDD/linux.tgz ; tar xzf linux.tgz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget --progress=dot:mega https://github.com/lip6/libDDD/raw/osx/osx.tgz ; tar xzf osx.tgz ; fi
  - ./configure --enable-nolto --prefix=$PWD/usr/local/  --with-antlrc=$PWD/usr/local/   --with-antlrjar=$PWD/usr/local/lib/antlr-3.4-complete.jar CPPFLAGS="-I$(pwd)/usr/local/include" LDFLAGS="-L$(pwd)/usr/local/lib" || cat config.log
  - make
  - strip -s bin/its-reach
  - cp bin/its-reach website/its-reach
  - strip -s bin/gal2c
  - cp bin/gal2c website/gal2c
  - make install
  - tar cvzf $TRAVIS_OS_NAME.tgz usr/
  - mv $TRAVIS_OS_NAME.tgz website/
#  - make dist
#  - mv its*.tar.gz website/


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  target_branch: $TARGETBRANCH
  on:
    branch: master

after_deploy:
  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json"   -H "Travis-API-Version:3" -H "Authorization:token $APITOKEN" -d '{"request":{"message":"Triggered by LibITS build.","branch":"master"}}' https://api.travis-ci.org/repo/lip6%2FITS-CTL/requests
  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json"   -H "Travis-API-Version:3" -H "Authorization:token $APITOKEN" -d '{"request":{"message":"Triggered by LibITS build.","branch":"master"}}' https://api.travis-ci.org/repo/lip6%2FITS-LTL/requests
    
